// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inj

import (
	"github.com/nanozuki/crows.moe/mediavote/backend/adapter/repository"
	"github.com/nanozuki/crows.moe/mediavote/backend/core/service/auth"
	"github.com/nanozuki/crows.moe/mediavote/backend/core/service/gql"
	"github.com/nanozuki/crows.moe/mediavote/backend/server"
)

// Injectors from wire.go:

func InitServer() (*server.Server, error) {
	repositoryRepository, err := repository.NewRepository()
	if err != nil {
		return nil, err
	}
	resolver := &gql.Resolver{
		Repository: repositoryRepository,
	}
	directiveRoot := _wireDirectiveRootValue
	service := &auth.Service{
		Repository: repositoryRepository,
	}
	server := &server.Server{
		GqlResolvers:  resolver,
		GqlDirectives: directiveRoot,
		AuthService:   service,
	}
	return server, nil
}

var (
	_wireDirectiveRootValue = gql.DirectiveRoot
)
