# vi:ft=make

set shell := ["fish", "-c"]

image := "asia-southeast1-docker.pkg.dev/crows-moe/images/ema"

default:
	just --list

build-image TAG:
	docker build --platform=linux/amd64 -t {{image}}:{{TAG}} .
	docker push {{image}}:{{TAG}}

run-nomination:
	# do first: gcloud emulators firestore start --host-port=127.0.0.1:9000
	FIRESTORE_EMULATOR_HOST=127.0.0.1:9000 EMA_DEV_STAGE=Nomination pnpm run dev

run-voting:
	# do first: gcloud emulators firestore start --host-port=127.0.0.1:9000
	FIRESTORE_EMULATOR_HOST=127.0.0.1:9000 EMA_DEV_STAGE=Voting pnpm run dev

run-award:
	# do first: gcloud emulators firestore start --host-port=127.0.0.1:9000
	FIRESTORE_EMULATOR_HOST=127.0.0.1:9000 EMA_DEV_STAGE=Award pnpm run dev

gen-migration:
	# do first: docker run --rm --name ema-db -p 5432:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_USER=ema -e POSTGRES_DB=ema -d postgres
	EMA_POSTGRES_URL=postgresql://ema:ema@localhost:5432/ema pnpm drizzle-kit generate:pg

