# vi:ft=make

set shell := ["fish", "-c"]

proj := "github.com/nanozuki/crows.moe/mediavote-api/"

default:
	just --list

test-all:
	ENV=testing podman-compose run server go test ./...

test MODEL:
	ENV=testing podman-compose run server go test {{proj}}{{MODEL}}

run:
	ENV=dev podman-compose up

down:
	podman-compose down -v

gen:
	go generate

build-image TAG:
	podman build -t ghcr.io/nanozuki/mediavote-api:{{TAG}} .
	podman push ghcr.io/nanozuki/mediavote-api:{{TAG}}
