# vi:ft=make

set shell := ["fish", "-c"]

proj := "github.com/nanozuki/crows.moe/cmd/ema-import/"
image := "asia-east1-docker.pkg.dev/crows-moe/images/mediavote-api"

default:
	just --list

test-all:
	ENV=testing docker-compose run server go test ./...

test MODEL:
	ENV=testing docker-compose run server go test {{proj}}{{MODEL}}

run-nomination:
	# do first: gcloud emulators firestore start --host-port=127.0.0.1:9000
	FIRESTORE_EMULATOR_HOST=127.0.0.1:9000 MEDIAVOTE_ENV=dev MEDIAVOTE_DEV_STAGE=Nomination go run *.go

run-voting:
	# do first: gcloud emulators firestore start --host-port=127.0.0.1:9000
	FIRESTORE_EMULATOR_HOST=127.0.0.1:9000 MEDIAVOTE_ENV=dev MEDIAVOTE_DEV_STAGE=Voting go run *.go

run-award:
	# do first: gcloud emulators firestore start --host-port=127.0.0.1:9000
	FIRESTORE_EMULATOR_HOST=127.0.0.1:9000 MEDIAVOTE_ENV=dev MEDIAVOTE_DEV_STAGE=Award go run *.go

down:
	docker-compose down -v

gen:
	go generate

build-image TAG:
	docker build --platform=linux/amd64 -t {{image}}:{{TAG}} .
	docker push {{image}}:{{TAG}}
